import Head from "next/head";
import Image from "next/image";
import navLogo from "../public/images/logo.jpg";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="shadow-xl">
        <nav className=" px-4 py-2 flex flex-wrap items-center gap-2 sm:gap-4 md:gap-10">
          <div className="flex gap-2 items-center">
            <Image src={navLogo} alt="navbar-logo" width={80} />
            <h1 className="text-2xl md:text-4xl font-black text-[#071849]">
              Rayzor{" "}
              <span className=" text-lg font-normal underline decoration-wavy ">
                Watersport
              </span>
            </h1>
          </div>

          <ul className="flex gap-2  text-lg text-[#071849]">
            <li className="cursor-pointer">Home</li>
            <li className="cursor-pointer">Contacts</li>
          </ul>
        </nav>
      </header>

      <main className="bg-sky-100 min-h-screen px-4 py-2">
        <h1 className="text-4xl font-black text-[#071849]">
          Whereas recognition of the inherent dignity
        </h1>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae
          distinctio fuga assumenda animi rerum ut blanditiis officia, totam
          ipsum consequuntur?
        </p>
      </main>
    </div>
  );
}
